function dummyboardGUI(DB)
%

%  By Luca Cavazzana for Politecnico di Milano
%  luca.cavazzana@gmail.com

DB.move = 0;

sizeGUI = [160,160];

f = figure('Visible', 'off', ...
    'Name', 'Select gesture', ...
    'NumberTitle', 'off', ...
    'Menubar', 'None', ...
    'Resize', 'off', ...
    'Position',[100, 100, sizeGUI]);

hHandClose = uicontrol('Style', 'text', ...
    'String', 'Select gesture' ,'Position', [5,135,150,20]);

hHandClose = uicontrol('Style', 'pushbutton', ...
    'String', 'Hand Close' ,'Position', [5,110,75,25], ...
    'Callback', {@pushCallback,1});

hHandOpen = uicontrol('Style', 'pushbutton', ...
    'String', 'Hand Open' ,'Position', [80,110,75,25], ...
    'Callback', {@pushCallback,2});

hWrExt = uicontrol('Style', 'pushbutton', ...
    'String', 'Wrist Ext' ,'Position', [5,85,75,25], ...
    'Callback', {@pushCallback,3});

hWrFlex = uicontrol('Style', 'pushbutton', ...
    'String', 'Wrist Flex' ,'Position', [80,85,75,25], ...
    'Callback', {@pushCallback,4});

hThAbd = uicontrol('Style', 'pushbutton', ...
    'String', 'Thum Abd' ,'Position', [5,60,75,25], ...
    'Callback', {@pushCallback,5});

hThOpp = uicontrol('Style', 'pushbutton', ...
    'String', 'Thum Opp' ,'Position', [80,60,75,25], ...
    'Callback', {@pushCallback,6});

hIndExt = uicontrol('Style', 'pushbutton', ...
    'String', 'Index Ext' ,'Position', [5,35,75,25], ...
    'Callback', {@pushCallback,7});

hExit = uicontrol('Style', 'pushbutton', ...
    'String', 'Exit' ,'Position', [80,5,75,25], ...
    'Callback', {@exitCallback});

set(f,'Visible','on');
drawnow;

    function pushCallback(source, eventdata, gesture)
        DB.move = gesture;
        DB.gTime = toc;
        drawnow;
    end

    function exitCallback(source, eventdata)
    end

end